---
# This Playbook deploys Kerberos 

- hosts: krb
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  tasks:
  - include: tasks/main.yml
  #- include: tasks/sssd.yml
  handlers:
   - include: handlers/main.yml
