---
# This Playbook deploys Kerberos 

- hosts: krb
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles: 
    - apt-update
  tasks:
  - include: tasks/main.yml
  handlers:
   - include: handlers/main.yml
