---

- name: krb | install kerberos packages
  action: apt pkg=$item state=installed
  with_items:
    - krb5-kdc
    - krb5-admin-server
  tags: krb auth 

- name: krb | ensure there is a done directory
  file: path=$krb_done_dir state=directory owner=root group=root
  tags: krb auth 

- name: krb | ensure krb5.conf exists
  template: src=root/etc/krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root
  tags: krb auth 
  when: krb_include_krb5_conf

- name: krb | ensure realm is created (This can take a very long time)
  shell: kdb5_util -r $krb_realm -P $krb_master_password create -s && touch $krb_create_realm_done creates=$krb_create_realm_done
  tags: krb auth 

- name: krb | ensure krb5-kdc is started
  service: name=krb5-kdc state=started
  tags: krb auth 

- name: krb | ensure krb5-admin-server is started
  service: name=krb5-admin-server state=started
  tags: krb auth 

- name: krb | ensure kadm5.acl exists
  template: src=root/etc/krb5kdc/kadm5.acl.j2 dest=/etc/krb5kdc/kadm5.acl owner=root group=root
  notify:
    - restart krb5-admin-server 
  tags: krb auth 
